services:
  real-estate:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5433;Database=RealEstateManagement;Username=postgres;Password=123456

  real-estate-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: RealEstateManagement
    ports:
      - "5433:5433"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
